// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7O5Euc5A7hjLDCfofPlKvNi7g8KQ0FdM',
    appId: '1:856868711309:web:16e5c1fc713889058f2bc4',
    messagingSenderId: '856868711309',
    projectId: 'yfghj-465c3',
    authDomain: 'yfghj-465c3.firebaseapp.com',
    storageBucket: 'yfghj-465c3.appspot.com',
    measurementId: 'G-JTC0Z9KZMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUqQ64VJ-0I3V8_7jcQTLOQUitub-IcE',
    appId: '1:856868711309:android:733916e1771822358f2bc4',
    messagingSenderId: '856868711309',
    projectId: 'yfghj-465c3',
    storageBucket: 'yfghj-465c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8UwgIIgTz_a5XbVAcEqNcYVcp-gfr8Q',
    appId: '1:856868711309:ios:176a92e2d58a2a538f2bc4',
    messagingSenderId: '856868711309',
    projectId: 'yfghj-465c3',
    storageBucket: 'yfghj-465c3.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8UwgIIgTz_a5XbVAcEqNcYVcp-gfr8Q',
    appId: '1:856868711309:ios:e5254aebab9482d18f2bc4',
    messagingSenderId: '856868711309',
    projectId: 'yfghj-465c3',
    storageBucket: 'yfghj-465c3.appspot.com',
    iosBundleId: 'com.example.chatbot.RunnerTests',
  );
}
